version: '3.8'
services:
    postgres:
        image: postgres
        #volumes:
            #- ./01-basegeografica.sql:/docker-entrypoint-initdb.d/01-basegeografica.sql
            #- ./02-basegeografica.sql:/docker-entrypoint-initdb.d/02-basegeografica.sql
        environment:
            POSTGRES_PASSWORD: "123456"
        ports:
            - "5432:5432"
    redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes:
            - cache:/data
    app:
        build: .
        image: app:1.0
        ports:
            - '8080:8080'
        environment:
            - API_AWESOME_BASE_URL = https://economia.awesomeapi.com.br
            - DATABASE_HOST=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=123456
            - DATABASE_NAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_TIMEZONE=America/Sao_Paulo
            - CACHE_HOST=redis
            - CACHE_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
            - CACHE_PORT=6379
        links:
            - "postgres:postgres"
            - "redis:redis"
        depends_on:
            - postgres
            - redis
volumes:
    cache:
        driver: local